# Generated by Django 2.2.23 on 2021-05-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='imagehu',
        ),
    ]
