# Generated by Django 2.2.23 on 2021-05-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210528_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imagehu',
            new_name='image',
        ),
    ]
